mod_md_authority: production

mod_md_extra_domains:
- imap.robots.org.uk
- smtp.robots.org.uk
- mail-in.robots.org.uk

mta_sts_domains:
- robots.org.uk
- meights.co.uk
- velse.co.uk

postfix_services:
  submissions/inet:
    command: smtpd
    private: 'n'
    flags:
      syslog_name: postfix/submissions
      smtpd_tls_wrappermode: 'yes'
      smtpd_sasl_auth_enable: 'yes'
      local_header_rewrite_clients: static:all
      smtpd_reject_unlisted_recipient: 'no'
      milter_macro_daemon_name: ORIGINATING
      smtpd_tls_cert_file: ~
      smtpd_tls_key_file: ~
      smtpd_tls_chain_files: >-
        /etc/pki/tls/private/postfix-msa-ecdsa.key
        /etc/pki/tls/certs/postfix-msa-ecdsa.crt
        /etc/pki/tls/private/postfix-msa-rsa.key
        /etc/pki/tls/certs/postfix-msa-rsa.crt
      smtpd_sasl_type: dovecot
      smtpd_sasl_path: /run/dovecot/postfix
      smtpd_sasl_tls_security_options: noanonymous
      smtpd_client_restrictions: >-
        reject_unauth_pipelining
      smtpd_helo_restrictions: >-
        reject_invalid_helo_hostname
      smtpd_sender_restrictions: >-
        reject_authenticated_sender_login_mismatch
        permit_sasl_authenticated
        reject
      smtpd_sender_login_maps: >-
        regexp:{ { /@(.+)\.ipa\.robots\.org\.uk$$/ = smtp/$$1.ipa.robots.org.uk@ipa.robots.org.uk }  }
        ldap:/etc/postfix/ldap-aliases.cf
        ldap:/etc/postfix/ldap-mailbox-logins.cf
      smtpd_relay_restrictions: >-
        permit_sasl_authenticated
        reject
      smtpd_recipient_restrictions: >-
        reject_unknown_recipient_domain
      smtpd_banner: 'smtp.robots.org.uk ESMTP $mail_name'
      line_length_limit: 4096  # for GSSAPI with large session tickets
      smtpd_tls_security_level: encrypt
      smtpd_tls_mandatory_protocols: '>=TLSv1.2'
      smtpd_tls_mandatory_ciphers: high
      tls_high_cipherlist: '{{ cipher_list }}'

postfix_config:
  inet_interfaces: all

  virtual_alias_domains: ''
  virtual_alias_maps: >-
    proxy:socketmap:unix:/run/postfix-sssd-ifp.sock:mail
    ldap:/etc/postfix/ldap-aliases.cf

  virtual_mailbox_domains: ldap:/etc/postfix/ldap-domains.cf
  virtual_transport: lmtp:unix:/run/dovecot/lmtp

  smtpd_tls_auth_only: 'yes'
  smtpd_sasl_security_options: noanonymous noplaintext
  smtpd_sasl_tls_security_options: noanonymous mutual_auth

  smtpd_authorized_xclient_hosts: ~

  smtpd_client_restrictions: >-
    reject_unauth_pipelining
    reject_unknown_client_hostname
  smtpd_helo_required: 'yes'
  smtpd_helo_restrictions: >-
    reject_invalid_helo_hostname
    reject_non_fqdn_helo_hostname
    reject_unknown_helo_hostname
  strict_rfc821_envelopes: 'yes'
  smtpd_reject_unlisted_sender: 'yes'
  smtpd_sender_restrictions: >-
    reject_unknown_sender_domain
  smtpd_relay_restrictions: >-
    reject_unauth_destination
  smtpd_reject_unlisted_recipient: 'yes'  # on by default anyway
  smtpd_recipient_restrictions: >-
    reject_unverified_recipient
  smtpd_tls_cert_file: ~
  smtpd_tls_key_file: ~
  smtpd_tls_chain_files: >-
    /etc/pki/tls/private/postfix-mta-ecdsa.key
    /etc/pki/tls/certs/postfix-mta-ecdsa.crt
    /etc/pki/tls/private/postfix-mta-rsa.key
    /etc/pki/tls/certs/postfix-mta-rsa.crt

  mynetworks: ''  # keep in sync with rspamd local_addrs

  # the default is still bdb:
  address_verify_map: $default_database_type:$data_directory/verify_cache

  unverified_recipient_reject_code: 450  # default; change to 550?

  relay_domains: ''

  smtpd_milters: inet:localhost:11332
  non_smtpd_milters: inet:localhost:11332
  milter_default_action: tempfail
  milter_protocol: 6

  recipient_delimiter: +-

  smtpd_tls_security_level: may
  tls_preempt_cipherlist: 'yes'

  smtp_helo_name: 'mail-out.robots.org.uk'
  smtp_bind_address_enforce: 'yes'
  smtp_bind_address6: '2a01:4f8:1c19:ad06::25:2'

  smtpd_banner: 'mail-in.robots.org.uk ESMTP $mail_name'

  smtpd_sasl_authenticated_header: 'no'  # default anyway

  #smtpd_recipient_limit = 1  # required for per-user statistics to work when rspamd is called as a milter?

cipher_list: PROFILE=SYSTEM:!kRSA:!SHA1:!SHA256:!SHA384:!AESCCM

dmarc_report_viewer_imap_password: !vault |
          $ANSIBLE_VAULT;1.2;AES256;robots-ansible
          64633330386435636437663233333538363932353535303034633963306336363238303636333738
          3761316236356434343638353237343161623134383331340a616531396239663764316462373639
          34303662383538643462666538653839653131663261353462393666666161633436343535356365
          3665346461656437370a363361363137343630636363653238343364373664306638633332383361
          63356337316466633331623533336430303136346539363062623637396137363737363264643138
          3835343730613930396534343366373932356139303665386435

dmarc_report_viewer_http_server_password: !vault |
          $ANSIBLE_VAULT;1.2;AES256;robots-ansible
          65613435376437336261313062323137326331346631363861623963646139616662356663646135
          6330633930386134303464326533353162303937386235330a346664356535386432623064656664
          62356237396130386332313839613034373631333531306633633566616336346564626137376137
          3531393563356633310a623434333536656433306163623030336436366337623165626666373630
          66303936316461386465313761616236376266353232643932623266366337666335393336633133
          3764373233626330386435613132373637353034646533666436
