mod_md_authority: production

mod_md_extra_domains:
- imap.robots.org.uk
- smtp.robots.org.uk
- mail-in.robots.org.uk

mta_sts_domains:
- robots.org.uk
- meights.co.uk
- velse.co.uk

postfix_services:
  submissions/inet:
    command: smtpd
    private: 'n'
    flags:
      syslog_name: postfix/submissions
      smtpd_tls_wrappermode: 'yes'
      smtpd_sasl_auth_enable: 'yes'
      local_header_rewrite_clients: static:all
      smtpd_reject_unlisted_recipient: 'no'
      milter_macro_daemon_name: ORIGINATING
      smtpd_tls_cert_file: /etc/pki/tls/certs/postfix-msa.pem
      smtpd_tls_key_file: /etc/pki/tls/private/postfix-msa.key
      smtpd_sasl_type: dovecot
      smtpd_sasl_path: /run/dovecot/postfix
      smtpd_sasl_tls_security_options: noanonymous
      smtpd_helo_restrictions: ""
      smtpd_sender_restrictions: >-
        reject_authenticated_sender_login_mismatch
        permit_sasl_authenticated
        reject
      smtpd_sender_login_maps: >-
        ldap:/etc/postfix/ldap-aliases.cf
        ldap:/etc/postfix/ldap-mailbox-logins.cf
      smtpd_relay_restrictions: >-
        permit_sasl_authenticated
        reject
      smtpd_recipient_restrictions: >-
        reject_unknown_recipient_domain
      smtpd_banner: 'smtp.robots.org.uk ESMTP $mail_name'
      line_length_limit: 4096  # for GSSAPI with large session tickets

postfix_config:
  inet_interfaces: all

  virtual_alias_domains: ''
  virtual_alias_maps: >-
    proxy:socketmap:unix:/run/postfix-sssd-ifp.sock:mail
    ldap:/etc/postfix/ldap-aliases.cf

  virtual_mailbox_domains: ldap:/etc/postfix/ldap-domains.cf
  virtual_transport: lmtp:unix:/run/dovecot/lmtp

  smtpd_tls_auth_only: 'yes'
  smtpd_sasl_security_options: noanonymous noplaintext
  smtpd_sasl_tls_security_options: noanonymous mutual_auth

  smtpd_authorized_xclient_hosts: ~

  smtpd_client_restrictions: >-
    reject_unauth_pipelining
  smtpd_helo_required: 'yes'
  smtpd_helo_restrictions: >-
    reject_invalid_helo_hostname
    reject_non_fqdn_helo_hostname
    reject_unknown_helo_hostname
  strict_rfc821_envelopes: 'yes'
  smtpd_reject_unlisted_sender: 'yes'
  smtpd_sender_restrictions: >-
    reject_unknown_sender_domain
  smtpd_relay_restrictions: >-
    reject_unauth_destination
  smtpd_reject_unlisted_recipient: 'yes'  # on by default anyway
  smtpd_recipient_restrictions: ~  # RBLs would go here

  mynetworks: ''  # keep in sync with rspamd local_addrs

  # the default is still bdb:
  address_verify_map: $default_database_type:$data_directory/verify_cache

  unverified_recipient_reject_code: 450  # default; change to 550?

  relay_domains: ''

  smtpd_milters: inet:localhost:11332
  non_smtpd_milters: inet:localhost:11332
  milter_default_action: tempfail
  milter_protocol: 6

  recipient_delimiter: +-

  smtpd_tls_security_level: may

  smtp_helo_name: 'mail-out.robots.org.uk'
  smtp_bind_address_enforce: 'yes'
  smtp_bind_address6: '2a01:4f8:1c19:ad06::25:2'

  smtpd_banner: 'mail-in.robots.org.uk ESMTP $mail_name'

  smtpd_sasl_authenticated_header: 'no'  # default anyway

  #smtpd_recipient_limit = 1  # required for per-user statistics to work when rspamd is called as a milter?
