mod_md_authority: staging

mod_md_extra_domains:
- imap.robots.org.uk
- smtp.robots.org.uk
- mail-in.robots.org.uk

mta_sts_domains:
- robots.org.uk
- meights.co.uk
- velse.co.uk

postfix_services:
  submissions/inet:
    command: smtpd
    private: 'n'
    flags:
      syslog_name: postfix/submissions
      smtpd_tls_wrappermode: 'yes'
      smtpd_sasl_auth_enable: 'yes'
      local_header_rewrite_clients: static:all
      smtpd_reject_unlisted_recipient: 'no'
      milter_macro_daemon_name: ORIGINATING
      smtpd_tls_cert_file: /etc/pki/tls/certs/postfix-msa.pem
      smtpd_tls_key_file: /etc/pki/tls/private/postfix-msa.key

postfix_config:
  virtual_alias_domains: ''
  virtual_alias_maps: >-
    proxy:socketmap:unix:/run/postfix-sssd-ifp.sock:mail
    ldap:/etc/postfix/ldap-aliases.cf

  virtual_mailbox_domains: ldap:/etc/postfix/ldap-domains.cf
  virtual_transport: lmtp:unix:/run/dovecot/lmtp

  smtpd_authorized_xclient_hosts: ~

  smtpd_recipient_restrictions: >-
    permit_sasl_authenticated
    reject_unauth_destination
    reject_unverified_recipient

  # the default is still bdb:
  address_verify_map: $default_database_type:$data_directory/verify_cache

  unverified_recipient_reject_code: 450  # default; change to 550?

  relay_domains: ''

  smtpd_milters: inet:localhost:11332
  non_smtpd_milters: inet:localhost:11332
  milter_default_action: tempfail
  milter_protocol: 6

  recipient_delimiter: +-

  smtpd_tls_security_level: may

  smtp_bind_address_enforce: 'yes'
  smtp_bind_address6: '2a01:4f8:1c19:ad06::25'

  #smtpd_recipient_limit = 1  # required for per-user statistics to work when rspamd is called as a milter?
