---
- hosts: all
  become: yes
  force_handlers: true
  tasks:
    - name: enable gssapi-keyex
      lineinfile:
        path: /etc/ssh/sshd_config
        line: GSSAPIKeyExchange yes
        regexp: (?i)^\s*GSSAPIKeyExchange\b
      notify: reload ssh

    - name: enable fstrim
      systemd:
        name: fstrim.timer
        state: started
        enabled: yes

    - name: install sssd-tools
      package:
        name: sssd-tools
        state: present

    - name: configure sssd debug_level
      ini_file:
        path: /etc/sssd/sssd.conf
        section: '{{item}}'
        option: debug_level
        value: '2'
      notify: restart sssd
      loop:
        - domain/ipa.robots.org.uk
        - sssd
        - nss
        - pam
        - sudo

  handlers:
    - name: restart ssst
      systemd:
        name: sssd
        state: restarted
    - name: reload ssh
      systemd:
        name: '{{s[ansible_facts.os_family]}}'
        state: reloaded
      when: ansible_facts.os_family == 'Debian'
      vars:
        s:
          Debian: ssh
          RedHat: sshd
