---
- hosts: ipaservers
  become: yes
  force_handlers: true
  tasks:
    - name: disable password authentication for root via SSH
      lineinfile:
        path: /etc/ssh/sshd_config
        line: PermitRootLogin prohibit-password
        regexp: (?i)^\s*PermitRootLogin\b
      notify: reload ssh

    - name: install firewalld
      yum: name=firewalld state=present
    - name: start firewalld
      systemd: name=firewalld state=started enabled=yes

    - name: recon firewalld log-denied
      command: firewall-cmd --get-log-denied
      check_mode: no
      changed_when: False
      register: firewalld_log_denied
    - name: set firewalld log-denied
      command: firewall-cmd --set-log-denied=unicast
      when: firewalld_log_denied.stdout != 'unicast'

    - name: recon firewalld default zone
      command: firewall-cmd --get-default-zone
      check_mode: no
      changed_when: False
      register: firewalld_default_zone
    - name: set firewalld default zone
      command: firewall-cmd --set-default-zone=public
      when: firewalld_default_zone.stdout != 'public'

    - name: firewall service configuration
      firewalld:
        zone: public
        service: '{{item.service}}'
        state: '{{item.state}}'
        permanent: yes
        immediate: yes
      loop:
        - {service: 'dns', state: 'enabled'}
        - {service: 'freeipa-ldap', state: 'enabled'}
        - {service: 'freeipa-ldaps', state: 'enabled'}
        - {service: 'freeipa-replication', state: 'enabled'}

    - name: set named to be authoritative-only
      lineinfile:
        path: /etc/named.conf
        line: "\trecursion no;"
        regexp: (?i)^\s*recursion\b
        insertafter: \ballow-recursion\b
      notify: reload bind

    - name: configure httpd mod_nss security
      when: "'mod_nss' in ansible_facts.packages"
      lineinfile:
        path: /etc/httpd/conf.d/nss.conf
        line: '{{item.name}} {{item.value}}'
        regexp: (?i)^\s*{{item.name}}\b
      loop:
        - {'name': 'NSSProtocol', 'value': '{{protocol|join(",")}}'}
        - {'name': 'NSSCipherSuite', 'value': '{{ciphersuite|join(",")}}'}
      vars:
        protocol:
          - TLSv1.2
        ciphersuite:
          - +aes_128_sha_256
          - +aes_256_sha_256
          - +ecdhe_ecdsa_aes_128_gcm_sha_256
          - +ecdhe_ecdsa_aes_128_sha
          - +ecdhe_ecdsa_aes_256_gcm_sha_384
          - +ecdhe_ecdsa_aes_256_sha
          - +ecdhe_rsa_aes_128_gcm_sha_256
          - +ecdhe_rsa_aes_128_sha
          - +ecdhe_rsa_aes_256_gcm_sha_384
          - +ecdhe_rsa_aes_256_sha
          - +rsa_aes_128_gcm_sha_256
          - +rsa_aes_128_sha
          - +rsa_aes_256_gcm_sha_384
          - +rsa_aes_256_sha
      notify: restart httpd

    - name: configure httpd mod_ssl security
      when: "'mod_ssl' in ansible_facts.packages"
      lineinfile:
        path: /etc/httpd/conf.d/ssl.conf
        line: '{{item.name}} {{item.value}}'
        regexp: (?i)^\s*{{item.name}}\b
      loop:
        - {'name': 'SSLProtocol', 'value': '{{protocol|join(" ")}}'}
      vars:
        protocol:
          - +TLSv1.2

    - name: configure slapd security
      ldap_attr:
        server_uri: ldapi://%2fvar%2frun%2fslapd-IPA-ROBOTS-ORG-UK.socket
        dn: '{{item.dn}}'
        name: '{{item.name}}'
        values: '{{item.value}}'
        state: exact
      loop:
        - {'dn': 'cn=encryption,cn=config', 'name': 'sslVersionMin', 'value': 'TLS1.2'}
        - {'dn': 'cn=config', 'name': 'nsslapd-minssf', 'value': '56'}
        - {'dn': 'cn=config', 'name': 'nsslapd-allow-anonymous-access', 'value': 'rootdse'}
        - {'dn': 'cn=config', 'name': 'nsslapd-require-secure-binds', 'value': 'on'}
      notify: restart slapd

    - name: restrict tomcat to TLSv1.2
      xml:
        path: /etc/pki/pki-tomcat/server.xml
        xpath: /Server/Service[@name='Catalina']/Connector[@name='Secure']
        attribute: '{{item}}'
        value: 'tls1_2:tls1_2'
      loop:
        - sslVersionRangeDatagram
        - sslVersionRangeStream
      notify: restart tomcat

  handlers:
    - name: reload ssh
      systemd: name=sshd state=reloaded
    - name: reload firewalld
      systemd: name=firewalld state=restarted
    - name: reload bind
      systemd: name=named-pkcs11 state=reloaded
    - name: restart httpd
      systemd: name=httpd state=restarted
    - name: restart slapd
      systemd: name=dirsrv@IPA-ROBOTS-ORG-UK state=restarted
    - name: restart tomcat
      systemd: name=pki-tomcatd@pki-tomcat state=restarted
