---
- hosts: samhosts
  become: yes
  force_handlers: true
  tasks:
    - name: configure log access
      user:
        name: sam
        groups: systemd-journal
        append: true

    - name: configure polkit admin rules
      copy:
        src: files/polkit/rules/20-robots.rules
        dest: /etc/polkit-1/rules.d
        owner: root
        group: root
        mode: 0644
        seuser: system_u
        serole: object_r
        setype: etc_t
      when: ansible_facts['os_family'] == 'RedHat'

    - name: configure policykit localauthority
      copy:
        src: files/polkit/rules/60-robots.conf
        dest: /etc/polkit-1/localauthority.conf.d
        owner: root
        group: root
        mode: 0644
      when: ansible_facts['os_family'] == 'Debian'

    #- name: recon default firewalld zone
      #changed_when: False
      #check_mode: False
      #command: firewall-cmd --get-default-zone
      #register: firewalld_default_zone
    #- name: set default firewalld zone
      #command: firewall-cmd --set-default-zone=public
      #when: firewalld_default_zone != 'public'

    - name: enable sssd infopipe responder
      when:
        ansible_facts['os_family'] == 'Debian'
      block:
        - name: install sssd-dbus
          apt:
            name: sssd-dbus
            state: present
        - name: enable sssd-dbus
          ini_file:
            path: /etc/sssd/sssd.conf
            section: sssd
            option: services
            value: nss, sudo, pam, ssh, ifp
          notify: restart sssd

  handlers:
    - name: restart sssd
      systemd:
        name: sssd
        state: restarted
