---
- hosts: samhosts
  become: yes
  force_handlers: true
  tasks:
    - name: gather package_facts
      package_facts:
    - name: configure log access
      user:
        name: sam
        groups: systemd-journal
        append: true

    - name: configure polkit admin rules
      copy:
        src: files/polkit/rules/20-robots.rules
        dest: /etc/polkit-1/rules.d
        owner: root
        group: root
        mode: 0644
        seuser: system_u
        serole: object_r
        setype: etc_t
      when: ansible_facts['os_family'] == 'RedHat'

    - name: configure policykit localauthority
      copy:
        src: files/polkit/rules/60-robots.conf
        dest: /etc/polkit-1/localauthority.conf.d
        owner: root
        group: root
        mode: 0644
      when: ansible_facts['os_family'] == 'Debian'

    #- name: recon default firewalld zone
      #changed_when: False
      #check_mode: False
      #command: firewall-cmd --get-default-zone
      #register: firewalld_default_zone
    #- name: set default firewalld zone
      #command: firewall-cmd --set-default-zone=public
      #when: firewalld_default_zone != 'public'

    - name: install sssd-dbus
      package:
        name: sssd-dbus
        state: present
    - name: enable sssd infopipe responder
      when:
        - ansible_facts.os_family == 'Debian'
        - ansible_facts.packages.sssd[0].version is version('2', '<')
      ini_file:
        path: /etc/sssd/sssd.conf
        section: sssd
        option: services
        value: nss, sudo, pam, ssh, ifp
      notify: restart sssd
    - name: use socket-activated responders
      when:
        - ansible_facts.os_family == 'Debian'
        - ansible_facts.packages.sssd[0].version is version('2', '>=')
      ini_file:
        path: /etc/sssd/sssd.conf
        section: sssd
        option: services
        state: absent
      notify: restart sssd

    # https://pagure.io/SSSD/sssd/issue/4045
    - name: disable socket-activated pac responder
      systemd:
        name: sssd-pac.socket
        state: stopped
        enabled: false
    - name: ensure socket-activated pac responder is not running
      systemd:
        name: sssd-pac.service
        state: stopped

    - name: enable sssd kerberos credentials manager
      when:
        ansible_facts['os_family'] == 'Debian'
      block:
        - name: install sssd-kcm
          apt:
            name: sssd-kcm
            state: present
        - name: configure libkrb5 to use KCM
          copy:
            src: files/krb5/debian
            dest: /etc/krb5.conf.d
            owner: root
            group: root
            mode: 0644

    # https://pagure.io/SSSD/sssd/issue/4047
    - name: force periodic dynamic dns updates
      ini_file:
        path: /etc/sssd/sssd.conf
        section: domain/ipa.robots.org.uk
        option: dyndns_refresh_interval
        value: '300'
      notify: restart sssd

  handlers:
    - name: restart sssd
      systemd:
        name: sssd
        state: restarted
