---
- hosts: all
  become: yes
  tasks:
    - include_tasks: "{{ ansible_facts['distribution'] }}-{{ ansible_facts['distribution_major_version'] }}.yml"

- import_playbook: ipaservers.yml
- import_playbook: samhosts.yml
