---
- hosts: all
  gather_facts: no
  tasks:

  - name: assert limit
    run_once: yes
    assert:
      that:
      - 'ansible_limit is defined'
      fail_msg: Playbook must be run with a limit
      quiet: yes

- import_playbook: common.yml
- import_playbook: ipaservers.yml
- import_playbook: samhosts.yml
