---
- name: assert limit is specified
  hosts: all
  gather_facts: no
  tasks:

  - name: assert limit
    run_once: true
    assert:
      that:
      - 'ansible_limit is defined'
      fail_msg: Playbook must be run with a limit
      quiet: yes

- name: configure hosts
  hosts: all
  tasks:

  - import_tasks: tasks/crb.yml
    tags: crb

  - import_tasks: tasks/epel.yml
    tags: epel

  - import_tasks: tasks/etckeeper.yml
    tags: etckeeper

  - import_tasks: tasks/ipa-client.yml
    tags: ipa-client

  - import_tasks: tasks/packages.yml
    tags: packages

  - import_tasks: tasks/firewalld.yml
    tags: firewalld

  - import_role:
      name: chrony
    tags: chrony

- name: configure ipa servers
  hosts: ipaservers
  tasks:

  - import_role:
      name: ipa-server
    tags: ipa-server

- name: configure internet-facing ipa servers
  hosts: ipaservers_public
  tasks:

  - import_role:
      name: ipsec
    tags: ipsec

# TODO: firewalld-stn-ipsec firewall-stn-sources firewalld-public-reject firewalld-public-icmp-echo firewalld-log-unicast insights-client node-exporter certmonger-exporter(+firewalld) journal
...
