- name: recon mailstore user
  user:
    name: mailstore
  register: _mailserver_dovecot_mailstore_user

- name: configure dovecot
  template:
    src: dovecot-local.conf.j2
    dest: /etc/dovecot/local.conf
    mode: 0644
    owner: root
    group: root
  notify: 'mailserver : reload dovecot'

- name: configure dovecot ldap
  template:
    src: dovecot-ldap.conf.ext.j2
    dest: /etc/dovecot/dovecot-ldap.conf.ext
    mode: 0640
    owner: root
    group: dovecot
  notify: 'mailserver : reload dovecot'

- name: disable dovecot system authentication
  replace:
    path: /etc/dovecot/conf.d/10-auth.conf
    regexp: ^(!include auth-system.conf\.ext)
    replace: '#\1'

- name: check dovecot config
  shell: doveadm config > /dev/null
  check_mode: false
  changed_when: false

- name: start dovecot
  systemd_service:
    name: dovecot.service
    state: started
    enabled: yes

