- name: recon mailstore user
  user:
    name: mailstore
  register: _mailserver_dovecot_mailstore_user

- name: configure dovecot
  template:
    src: dovecot/local.conf.j2
    dest: /etc/dovecot/local.conf
    mode: 0644
    owner: root
    group: root
  notify: 'mailserver : reload dovecot'  # some settings need a restart

- name: Remove Dovecot DH parameters
  file:
    path: /etc/dovecot/dhparams-ffdhe3072.pem
    state: absent

- name: configure dovecot ldap
  template:
    src: dovecot/ldap.conf.ext.j2
    dest: /etc/dovecot/ldap.conf.ext
    mode: 0400
    owner: dovecot
    group: root
  notify: 'mailserver : reload dovecot'

- name: disable dovecot authentication includes
  replace:
    path: /etc/dovecot/conf.d/10-auth.conf
    regexp: ^(!include\s.*)
    replace: '#\1'

- name: create dovecot sieve script directory
  file:
    path: /etc/dovecot/sieve
    state: directory
    mode: 0755
    owner: root
    group: root

- name: check dovecot config
  shell: doveadm config > /dev/null
  check_mode: false
  changed_when: false

- name: configure dovecot sieve scripts
  include_tasks: dovecot-sieve.yml
  loop:
  - on-move.sieve
  - spam.sieve
  loop_control:
    loop_var: script

- name: create dovecot utility script directory
  file:
    path: /usr/local/libexec/dovecot
    state: directory
    mode: 0755
    owner: root
    group: root

- name: create dovecot dsync-server wrapper
  copy:
    src: dovecot/wrap-dsync-server.sh
    dest: /usr/local/libexec/dovecot/wrap-dsync-server
    mode: 0755
    owner: root
    group: root

- name: create dovecot auth wrapper
  copy:
    src: dovecot/wrap-auth.sh
    dest: /usr/local/libexec/dovecot/wrap-auth
    mode: 0755
    owner: root
    group: root
    setype: _default

- name: install dovecot_auth_wrap SELinux policy module
  import_role:
    name: selinux_policy
  vars:
    module_src: dovecot/dovecot_auth_wrap.cil
    state: present

- name: create dovecot sieve pipe script directory
  file:
    path: /usr/local/libexec/dovecot/sieve
    state: directory
    mode: 0755
    owner: root
    group: root

- name: install dovecot sieve pipe script
  copy:
    src: dovecot/{{ item }}
    dest: /usr/local/libexec/dovecot/sieve/{{ (item | splitext)[0] }}
    mode: 0755
    owner: root
    group: root
  loop:
  - rspamd-report.sh

- name: create dovecot.service local configuration directory
  file:
    path: /etc/systemd/system/dovecot.service.d
    state: directory
    mode: 0755
    owner: root
    group: root

- name: configure dovecot to require /srv/mail is mounted
  copy:
    content: |
      [Unit]
      ConditionPathIsMountPoint=/srv/mail
      ConditionPathIsDirectory=/srv/mail/domains
    dest:
      /etc/systemd/system/dovecot.service.d/require-mount.conf
    mode: 0644
    owner: root
    group: root
  notify: 'mailserver : systemctl daemon-reload'

- name: flush handlers
  meta: flush_handlers

- name: start dovecot
  systemd_service:
    name: dovecot.service
    state: started
    enabled: yes

- name: configure gssproxy for dovecot
  copy:
    src: dovecot/gssproxy.conf
    dest: /etc/gssproxy/80-dovecot.conf
    mode: 0600
    owner: root
    group: root
  notify: 'mailserver : reload gssproxy'

- name: populate keytab with kerberos keys for smtp/imap
  import_role:
    name: keytab
  vars:
    path: /etc/gssproxy/dovecot.keytab
    principals:
      - smtp/smtp.robots.org.uk@IPA.ROBOTS.ORG.UK
      - imap/imap.robots.org.uk@IPA.ROBOTS.ORG.UK
    extra_args: [-r]

- name: populate keytab with kerberos keys for sieve
  import_role:
    name: keytab
  vars:
    path: /etc/gssproxy/dovecot.keytab
    principals:
      - sieve/imap.robots.org.uk@IPA.ROBOTS.ORG.UK

- name: apply restrictive permissions to dovecot keytab
  file:
    path: /etc/gssproxy/dovecot.keytab
    mode: 0600
    owner: root
    group: root

- name: remove dovecot_keytab policy module
  import_role:
    name: selinux_policy
  vars:
    module_src: dovecot/dovecot_keytab.cil
    state: absent

- name: remove up dovecot's copy of the keytab
  file:
    path: /etc/dovecot/krb5.keytab
    state: absent

- name: allow smtp/submissions through firewall
  firewalld:
    service: "{{ item }}"
    state: enabled
    permanent: true
    immediate: true
  loop: [imaps, managesieve]
