- name: load mailstore selinux policy module
  include_role:
    name: selinux_policy
  vars:
    module_src: mailstore.cil

- name: create mail storage group
  group:
    name: mailstore
    system: true
    state: present

- name: create mail storage user
  user:
    name: mailstore
    group: mailstore
    system: true
    create_home: false
    home: /srv/mail
    password: '!*'
    state: present

- name: create mail storage directory
  file:
    path: /srv/mail
    state: directory
    mode: 0770
    owner: root
    group: mailstore
    setype: _default
