- name: load mailstore selinux policy module
  include_role:
    name: selinux_policy
  vars:
    module_src: mailstore.cil

- name: create mail storage group
  group:
    name: mailstore
    system: true
    state: present

- name: create mail storage user
  user:
    name: mailstore
    group: mailstore
    groups: remote-access  # temporary to allow replicator to SSH in
    system: true
    create_home: false
    home: /srv/mail
    password: '!*'
    state: present

- name: create mail storage directory
  file:
    path: /srv/mail
    state: directory
    mode: 0700
    owner: mailstore  # temporary to allow replicator to SSH in
    group: mailstore
    setype: _default

- name: configure mail storage ssh config directory
  file:
    path: /srv/mail/.ssh
    state: directory
    mode: 0500
    owner: mailstore
    group: mailstore

- name: configure mail storage authorized_keys
  copy:
    content: |
      from="2a03:b0c0:0:1010::64:e001,37.139.10.94" ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIEVdJ2znTpljtMD4S0cVaEwY8rBJnPRkxSZ3jk6iur5+ root@traxus.ipa.robots.org.uk
    dest: /srv/mail/.ssh/authorized_keys
    mode: 0400
    owner: mailstore
    group: mailstore

- name: permit remote access for mail storage user
  copy:
    content: |
      +:mailstore:2a03:b0c0:0:1010::64:e001
      +:mailstore:37.139.10.94
    dest: /etc/security/access.d/10_mailstore-dsync.conf
    mode: 0644
    owner: root
    group: root
