- name: install mailserver packages
  package:
    name:
    - mutt
    - postfix
    - postfix-ldap
    - dovecot
    - dovecot-pigeonhole
    - unbound
    - valkey
    state: present
  tags: slow
...
