- name: install mailserver packages
  package:
    name:
    - mutt
    - swaks
    - perl-Sys-Hostname  # swaks needs it
    - postfix
    - postfix-ldap
    - dovecot
    - dovecot-pigeonhole
    - unbound
    - valkey
    - httpd
    - mod_md
    state: present
  tags: slow
...
