- name: recon postconf {{ item.key }}
  command: postconf -ph {{ item.key }}
  check_mode: false
  changed_when: false
  register: _mailserver_postfix_postconf

- name: apply postconf {{ item.key }}
  command:
    argv:
    - postconf
    - -ep 
    - "{{ item.key }}={{ item.value }}"
  when: _mailserver_postfix_postconf.stdout != item.value|string
  notify: 'mailserver : reload postfix'
