# {{{  postconf(5)
- name: recon postconf(5) effective settings
  command: postconf -p
  check_mode: false
  changed_when: false
  register: _mailserver_postfix_postconf

- name: recon postconf(5) explicit settings
  command: postconf -n
  check_mode: false
  changed_when: false
  register: _mailserver_postfix_postconf_n

- name: parse postconf(5)
  set_fact:
    postfix_postconf: >-
      {{
        dict(
          _mailserver_postfix_postconf.stdout_lines
          | map('split', '=', 1)
          | map('map', 'trim')
          | list
        )
      }}
    postfix_postconf_explicit: >-
      {{
        dict(
          _mailserver_postfix_postconf_n.stdout_lines
          | map('split', '=', 1)
          | map('map', 'trim')
          | list
        )
      }}

- name: figure postconf(5) changes
  set_fact:
    _postfix_postconf_edit_args: >-
      {{
        (_postfix_postconf_edit_args | default({}))
        |
        combine(
          {item.key: item.value}
            if item.value is not none
              and (item.value | string) != (postfix_postconf.get(item.key))
          else {}
        )
      }}
    _postfix_postconf_unset_args: >-
      {{
        (_postfix_postconf_unset_args | default([]))
        +
        (
          [item.key]
            if item.value is none
              and item.key in postfix_postconf_explicit
          else []
        )
      }}
    _postfix_postconf_args_needing_restart: >-
      {{
        (_postfix_postconf_args_needing_restart | default([]))
        +
        ([item.key] if item.key in _postfix_postconf_needs_restart else [])
      }}
  loop: "{{ postfix_config | dict2items }}"

- name: edit postconf(5) values
  command:
    argv: >-
      {% set args = ['postconf', '-ep'] -%}
      {% for k, v in _postfix_postconf_edit_args.items() -%}
        {% set _ = args.append(k ~ '=' ~ v) -%}
      {% endfor -%}
      {{ args }}
  when: _postfix_postconf_edit_args | default([]) | length > 0
  register: _postfix_postconf_e

- name: unset postconf(5) values
  command:
    argv: "{{ ['postconf', '-Xp'] + _postfix_postconf_unset_args }}"
  when: _postfix_postconf_unset_args | default([]) | length > 0
  register: _postfix_postconf_X

- name: reload/restart postconf(5)
  command: systemctl {{ (_postfix_postconf_args_needing_restart | length > 0) | ternary("try-restart", "try-reload-or-restart") }} postfix.service
  when: _postfix_postconf_e.changed or _postfix_postconf_X.changed
# }}}

- name: start postfix
  systemd_service:
    name: postfix.service
    state: started
    enabled: true

# {{{ ldap lookups
- name: configure ldap_table to look up virtual mailbox domains
  template:
    src: postfix/ldap_table.cf.j2
    dest: /etc/postfix/ldap-domains.cf
    mode: 0640
    owner: root
    group: postfix
  vars:
    scope: base
    search_base: mailDomainName=%s,cn=mail,dc=ipa,dc=robots,dc=org,dc=uk
    query_filter: (&(objectClass=mailDomain)(mailDomainName=%s))
    result_attribute: mailDomainName

- name: configure ldap_table to look up virtual aliases
  template:
    src: postfix/ldap_table.cf.j2
    dest: /etc/postfix/ldap-aliases.cf
    mode: 0640
    owner: root
    group: postfix
  vars:
    scope: base
    search_base: mail=%s,cn=mail,dc=ipa,dc=robots,dc=org,dc=uk
    query_filter: (&(objectClass=mailAlias)(mail=%s))
    result_attribute: mailRoutingAddress

- name: configure ldap_table to look up a mailbox's logins
  template:
    src: postfix/ldap_table.cf.j2
    dest: /etc/postfix/ldap-mailbox-logins.cf
    mode: 0640
    owner: root
    group: postfix
  vars:
    scope: base
    search_base: mail=%s,cn=mail,dc=ipa,dc=robots,dc=org,dc=uk
    query_filter: (&(objectClass=mailBox)(mail=%s))
    result_attribute: mail, memberPrincipal
# }}}

# {{{ master(5) services
- name: configure master(5) services
  include_tasks: postfix-service.yml
  loop: '{{ postfix_services|dict2items("name", "value") }}'
  loop_control:
    loop_var: service
# }}}

# {{{ /etc/aliases
- name: configure local alias for root
  lineinfile:
    line: 'root:    sam@robots.org.uk'
    path: /etc/aliases
    state: present
    regexp: '^#?root:'
    insertafter: EOF

- name: stat /etc/aliases
  stat:
    path: /etc/aliases
  register: _mailserver_aliases

- name: stat aliases db
  stat:
    path: /etc/aliases.lmdb
  register: _mailserver_aliases_db

- name: rebuild aliases db
  command: newaliases
  when: |
    not _mailserver_aliases_db.stat.exists
    or _mailserver_aliases.stat.mtime > _mailserver_aliases_db.stat.mtime
# }}}

- name: allow smtp/submissions through firewall
  firewalld:
    service: "{{ item }}"
    state: enabled
    permanent: true
    immediate: true
  loop: [smtp, smtps]

# vim: fdm=marker
