- include_tasks: postfix-postconf.yml
  loop: "{{ postfix_config | dict2items }}"

- name: configure ldap_table virtual domains
  template:
    src: ldap_table.cf.j2
    dest: /etc/postfix/ldap-domains.cf
    mode: 0640
    owner: root
    group: postfix
  vars:
    comment: Postfix will search for _just_ the domain name, so %s will be the domain name
    search_base: mailDomainName=%s,cn=mail,dc=ipa,dc=robots,dc=org,dc=uk
    scope: base
    query_filter: (objectClass=mailDomain)
    result_attribute: mailDomainName
    bind_pw: '{{ hostvars[groups["ipaservers"][0]]["ipa_server_dovecot_password"] }}'

- name: configure ldap_table virtual aliases
  template:
    src: ldap_table.cf.j2
    dest: /etc/postfix/ldap-aliases.cf
    mode: 0640
    owner: root
    group: postfix
  vars:
    comment: Search for a matching alias with the full email address, so %u and %d will work
    search_base: mailLocalPart=%u,mailDomainName=%d,cn=mail,dc=ipa,dc=robots,dc=org,dc=uk
    scope: base
    query_filter: (&(objectClass=mailAlias)(mail=*))
    result_attribute: mail
    bind_pw: '{{ hostvars[groups["ipaservers"][0]]["ipa_server_dovecot_password"] }}'

- name: configure ldap_table virtual mailboxes
  template:
    src: ldap_table.cf.j2
    dest: /etc/postfix/ldap-mailboxes.cf
    mode: 0640
    owner: root
    group: postfix
  vars:
    comment: Search for a matching mailbox with the full email address, so %u and %d will work
    search_base: mailLocalPart=%u,mailDomainName=%d,cn=mail,dc=ipa,dc=robots,dc=org,dc=uk
    scope: base
    query_filter: (objectClass=mailBox)
    result_attribute: mailLocalPart
    bind_pw: '{{ hostvars[groups["ipaservers"][0]]["ipa_server_dovecot_password"] }}'

- name: configure ldap_table virtual catchall
  template:
    src: ldap_table.cf.j2
    dest: /etc/postfix/ldap-catchall.cf
    mode: 0640
    owner: root
    group: postfix
  vars:
    comment: |
      Search for a catchall alias which looks like @domain; since this is not
      a valid email address, %s must be used.
    search_base: mailDomainName=%s,cn=mail,dc=ipa,dc=robots,dc=org,dc=uk
    query_filter: (&(objectClass=mailDomain)(mail=*))
    result_attribute: mail
    bind_pw: '{{ hostvars[groups["ipaservers"][0]]["ipa_server_dovecot_password"] }}'

- name: start postfix
  systemd_service:
    name: postfix.service
    state: started
    enabled: true
