# {{{ installation
- name: import rspamd PGP key
  rpm_key:
    state: present
    key: https://rspamd.com/apt-stable/gpg.key
    fingerprint: 3FA3 47D5 E599 BE45 95CA  2576 FFA2 32ED BF21 E25E

- name: enable rspamd repository
  get_url:
    url: https://rspamd.com/rpm-stable/centos-{{ ansible_facts.distribution_major_version }}/rspamd.repo
    dest: /etc/yum.repos.d/rspamd.repo
    mode: 0644
    owner: root
    group: root

- name: install rspamd
  package:
    name: rspamd
    state: present
  tags: slow
# }}}

# {{{ configuration
- name: configure rspamd
  copy:
    content: "{{ item.content }}"
    dest: /etc/rspamd/local.d/{{ item.filename }}
    mode: "{{ item.private|default(false) | ternary('0640', '0644') }}"
    owner: root
    group: "{{ item.private|default(false) | ternary('_rspamd', 'root') }}"
  notify: 'mailserver : reload rspamd'
  no_log: '{{ item.private|default(false) }}'
  loop:
  - filename: redis.conf
    content: |
      servers = "[::1]:6379";
      timeout = 1s;
      db = 0;
      username = "rspamd";
      password = "{{ lookup('ipa_vault', 'redis-password-rspamd', service='host/' ~ inventory_hostname) }}";
    private: true
  - filename: worker-proxy.inc
    content: |
      milter = yes;
      timeout = 120s;
      upstream "local" {
        default = yes;
        self_scan = yes;
      }
  - filename: worker-controller.inc
    private: true
    content: |
      password = "{{ lookup('ipa_vault', 'rspamd-password', service='host/' ~ inventory_hostname) }}";
      enable_password = "{{ lookup('ipa_vault', 'rspamd-enable-password', service='host/' ~ inventory_hostname) }}";
  - filename: worker-normal.inc
    content: |
      enabled = false;
  - filename: greylist.conf
    content: |
      timeout = 10min;
      message = "Temporary local problem. Sorry.";
  - filename: options.inc
    content: |
      dns {
        nameserver = ["[::1]:53"]
      }
      enable_test_patterns = false;
      local_addrs = ["[::1]/128", "127.0.0.0/8"];  # keep this in sync with postfix's mynetworks
  - filename: classifier-bayes.conf
    content: |
      expiry = 720 * 24 * 60 * 60;

      # rspamd as a milter gets called once per message, not per user
      per_user = false;

      autolearn {
        spam_threshold = 20; # vs default reject threshold (15)
        junk_threshold = 11; # vs default add_header threshold (6)
        ham_threshold = -0.5;
        check_balance = true;
      }
  - filename: milter_headers.conf
    content: |
      default_headers_order = 1;
      headers_modify_mode = "override";

      extended_spam_headers = true;  # x-spamd-result, x-rspamd-server, x-rspamd-queue-id, x-rspamd-action
      use = ["x-spamd-bar", "x-spam-status", "authentication-results"];
      #skip_local = false;
      #skip_authenticated = true;
      # remove-spam-flag is activated by default, which only removes X-Spam; what about other headers?
  - filename: dmarc.conf
    content: |
      #actions = {
      #  quarantine = "add_header";
      #  reject = "reject";
      #}

      reporting {
        enabled = true;
        email = "rpt@mta.robots.org.uk";
        domain = "robots.org.uk";
        org_name = "robots.org.uk";
        smtp = '::1';
      }
  - filename: known_senders.conf
    content: |
      enabled = true;

- name: create rspamd local allowlist directory
  file:
    path: /etc/rspamd/local.d/maps.d
    state: directory
    mode: 0o755
    owner: root
    group: root

- name: configure rspamd surbl whitelist
  copy:
    content: |
      sendgrid.net
    dest: /etc/rspamd/local.d/maps.d/surbl-whitelist.inc.local
    mode: 0o644
    owner: root
    group: root
# }}}

# {{{ controller UI
- name: Populate httpd keytab for rspamd
  import_role:
    name: keytab
  vars:
    path: /etc/gssproxy/httpd.keytab
    principals: [HTTP/rspamd.robots.org.uk@IPA.ROBOTS.ORG.UK]

#/etc/pki/tls/rspamd.crt
#/etc/pki/tls/private/rspamd.crt

- name: Create rspamd httpd vhost
  copy:
    src: rspamd/httpd.conf
    dest: /etc/httpd/conf.d/~rspamd.conf
    mode: 0644
    owner: root
    group: root
  notify: 'mailserver : reload apache'

- name: Create rspamd httpd log directory
  file:
    path: /var/log/httpd/rspamd.robots.org.uk
    state: directory
    mode: 0755
    owner: root
    group: root
# }}}

# {{{ dkim signing
- name: recon mailbox domains
  community.general.ldap_search:
    server_uri: '{{ groups["ipaservers_public"] | map("regex_replace", "^", "ldaps://") | join(",") }}'
    dn: cn=mail,dc=ipa,dc=robots,dc=org,dc=uk
    scope: onelevel
    filter: '(objectClass=mailDomain)'
    attrs:
    - mailDomainName
    bind_dn: uid=dovecot,cn=sysaccounts,cn=etc,dc=ipa,dc=robots,dc=org,dc=uk
    bind_pw: '{{ dovecot_password }}'
  check_mode: false
  register: _mailserver_rspamd_mailbox_domains

- name: figure virtual_mailbox_domains
  set_fact:
    mailserver_rspamd_mailbox_domains: '{{ _mailserver_rspamd_mailbox_domains.results | map(attribute="mailDomainName") | map("basename") | list }}'

- name: configure DKIM signing
  template:
    src: rspamd/dkim_signing.conf.j2
    dest: /etc/rspamd/local.d/dkim_signing.conf
    mode: 0644
    owner: root
    group: root
  notify: 'mailserver : reload rspamd'

- name: create DKIM key directory
  file:
    path: /etc/rspamd/dkim
    state: directory
    mode: 0750
    owner: root
    group: _rspamd

- name: generate DKIM keys
  include_tasks: rspamd-dkim.yml
  loop: '{{ mailserver_rspamd_mailbox_domains }}'
  loop_control:
    loop_var: domain
# }}}

- name: check rspamd config
  shell: rspamadm configtest --strict
  check_mode: false
  changed_when: false

- name: start rspamd
  systemd_service:
    name: rspamd.service
    state: started
    enabled: true

# {{{ dmarc reporting
- name: create DMARC reporting timer
  copy:
    content: |
      [Unit]
      Description=rspamd DMARC reporting
      Documentation=https://docs.rspamd.com/modules/dmarc/

      [Timer]
      OnCalendar=18:00
      AccuracySec=1h
      RandomizedDelaySec=1h

      [Install]
      WantedBy=timers.target
    dest: /etc/systemd/system/rspamd-dmarc-report.timer
    mode: 0o644
    owner: root
    group: root
  notify: 'systemctl daemon-reload'
  register: _mailserver_rspamd_dmarc_report_timer

- name: create DMARC reporting service
  copy:
    content: |
      [Unit]
      Description=rspamd DMARC reporting
      Documentation=https://docs.rspamd.com/modules/dmarc/

      [Service]
      Type=exec
      ExecStart=/usr/bin/rspamadm dmarc_report
      User=_rspamd
    dest: /etc/systemd/system/rspamd-dmarc-report.service
    mode: 0o644
    owner: root
    group: root
  notify: 'systemctl daemon-reload'

- meta: flush_handlers

- name: enable/start DMARC reporting timer
  systemd_service:
    name: rspamd-dmarc-report.timer
    state: '{{ _mailserver_rspamd_dmarc_report_timer.changed | ternary("restarted", "started") }}'
    enabled: true
# }}}

# vim: foldmethod=marker
