- name: import rspamd PGP key
  rpm_key:
    state: present
    key: https://rspamd.com/apt-stable/gpg.key
    fingerprint: 3FA3 47D5 E599 BE45 95CA  2576 FFA2 32ED BF21 E25E

- name: enable rspamd repository
  get_url:
    url: https://rspamd.com/rpm-stable/centos-{{ ansible_facts.distribution_major_version }}/rspamd.repo
    dest: /etc/yum.repos.d/rspamd.repo
    mode: 0644
    owner: root
    group: root

- name: install rspamd
  package:
    name: rspamd
    state: present
  tags: slow

- name: configure rspamd
  copy:
    content: "{{ item.content }}"
    dest: /etc/rspamd/local.d/{{ item.filename }}
    mode: "{{ item.private|default(false) | ternary('0640', '0644') }}"
    owner: root
    group: "{{ item.private|default(false) | ternary('_rspamd', 'root') }}"
  notify: 'mailserver : reload rspamd'
  loop:
  - filename: redis.conf
    content: |
      servers = "[::1]:6379";
      timeout = 1s;
      #db = "0";
      #password = "?";
    private: true
  - filename: worker-proxy.inc
    content: |
      milter = yes;
      timeout = 120s;
      upstream "local" {
        default = yes;
        self_scan = yes;
      }
  - filename: worker-normal.inc
    content: |
      enabled = false;
  - filename: greylist.conf
    content: |
      timeout = 10min;
      message = "Temporary local problem. Sorry.";
      #servers = "[::1]:6379";
      #password = "?";
    private: true
  - filename: options.inc
    content: |
      dns {
        nameserver = ["[::1]:53"]
      }
      enable_test_patterns = false;
      local_addrs = [];  # keep this in sync with postfix's mynetworks
  - filename: classifier-bayes.conf
    content: |
      expiry = 250 * 24 * 60 * 60;

      # rspamd as a milter gets called once per message, not per user
      per_user = false;

      autolearn {
        spam_threshold = 20; # vs default reject threshold (15)
        junk_threshold = 11; # vs default add_header threshold (6)
        ham_threshold = -0.5;
        check_balance = true;
      }
  - filename: milter_headers.conf
    content: |
      default_headers_order = 1;
      headers_modify_mode = "override";

      extended_spam_headers = true;  # x-spamd-result, x-rspamd-server, x-rspamd-queue-id, x-rspamd-action
      # not clear if these are pre-defined or whether we have to add the definitions to the use section...
      use = ["x-spamd-bar", "x-spam-level", "x-spam-status", "authentication-results"];
      #skip_local = false;
      #skip_authenticated = true;
      # remove-spam-flag is activated by default, which only removes X-Spam; what about other headers?

- name: recon mailbox domains
  community.general.ldap_search:
    server_uri: '{{ groups["ipaservers_public"] | map("regex_replace", "^", "ldaps://") | join(",") }}'
    dn: cn=mail,dc=ipa,dc=robots,dc=org,dc=uk
    scope: onelevel
    filter: '(objectClass=mailDomain)'
    attrs:
    - mailDomainName
    bind_dn: uid=dovecot,cn=sysaccounts,cn=etc,dc=ipa,dc=robots,dc=org,dc=uk
    bind_pw: '{{ dovecot_password }}'
  check_mode: false
  register: _mailserver_rspamd_mailbox_domains

- name: figure virtual_mailbox_domains
  set_fact:
    mailserver_rspamd_mailbox_domains: '{{ _mailserver_rspamd_mailbox_domains.results | map(attribute="mailDomainName") | map("basename") | list }}'

- name: configure DKIM signing
  template:
    src: rspamd/dkim_signing.conf.j2
    dest: /etc/rspamd/local.d/dkim_signing.conf
    mode: 0644
    owner: root
    group: root
  notify: 'mailserver : reload rspamd'

- name: create DKIM key directory
  file:
    path: /etc/rspamd/dkim
    state: directory
    mode: 0750
    owner: root
    group: _rspamd

- name: generate DKIM keys
  include_tasks: rspamd-dkim.yml
  loop: '{{ mailserver_rspamd_mailbox_domains }}'
  loop_control:
    loop_var: domain

- name: check rspamd config
  shell: rspamadm configtest --strict
  check_mode: false
  changed_when: false

- name: start rspamd
  systemd_service:
    name: rspamd.service
    state: started
    enabled: true

# TODO rspamadm pw
