- name: configure sssd infopipe service for postfix
  copy:
    src: sssd-ifp-postfix.conf
    dest: /etc/sssd/conf.d/ifp-postfix.conf
    mode: 0640
    owner: root
    group: sssd
  notify: 'mailserver : restart sssd'

- name: deploy sssd ifp lookup script
  copy:
    src: postfix-sssd-ifp.py
    dest: /usr/local/libexec/postfix-sssd-ifp
    mode: 0755
    owner: root
    group: root
  register: _postfix_sssd_ifp_script
  notify: 'mailserver : stop postfix-sssd-ifp'

- name: deploy sssd ifp lookup service
  copy:
    src: postfix-sssd-ifp.service
    dest: /etc/systemd/system/postfix-sssd-ifp.service
    mode: 0644
    owner: root
    group: root
  notify:
  - 'mailserver : systemctl daemon-reload'
  - 'mailserver : stop postfix-sssd-ifp'

- name: deploy sssd ifp lookup socket
  copy:
    src: postfix-sssd-ifp.socket
    dest: /etc/systemd/system/postfix-sssd-ifp.socket
    mode: 0644
    owner: root
    group: root
  notify:
  - 'mailserver : systemctl daemon-reload'
  - 'mailserver : restart postfix-sssd-ifp.socket'

- name: flush handlers
  meta: flush_handlers

- name: start sssd ifp lookup socket
  systemd_service:
    name: postfix-sssd-ifp.socket
    state: started
    enabled: true

- name: load sssd ifp selinux policy module
  include_role:
    name: selinux_policy
  vars:
    module_src: postfix-sssd-ifp.cil

