- name: install firewalld
  package:
    name: firewalld
    state: present
  tags: slow

- name: enable & start firewalld
  systemd_service:
    name: firewalld
    enabled: '{{ firewalld | ternary(true, false) }}'
    state: '{{ firewalld | ternary("started", "stopped") }}'
...
