- name: install ipa-client
  package:
    name: ipa-client
    state: present
  tags: slow

- name: install ipa-client scripts
  copy:
    src: files/ipa-client/akinit.py
    dest: /usr/local/bin/akinit
    mode: 0755
    owner: root
    group: root

- name: recon IPA client configured
  command:
    argv:
    - python3
    - -c
    - |
      from ipalib.facts import is_ipa_client_configured
      print(int(is_ipa_client_configured()))
  check_mode: false
  changed_when: false
  register: ipa_client_configured

- name: join host to domain
  when: not (ipa_client_configured.stdout | bool)
  block:
  - name: provide IPA CA certificate
    copy:
      src: /etc/ipa/ca.crt
      dest: /tmp/ipa-ca.crt

  - name: set host {{ inventory_hostname }} one-time password
    command: ipa host-mod {{ inventory_hostname }} --random --raw
    register: _ipa_client_otp_raw
    delegate_to: localhost
    become: false

  - name: extract host {{ inventory_hostname }} one-time password
    set_fact:
      _ipa_client_otp: "{{ (_ipa_client_otp_raw.stdout_lines | select('match', '^\\s*randompassword:') | first | split(':'))[1] | trim }}"

  - name: ipa-client-install
    command:
      argv:
      - ipa-client-install
      - --unattended
      - --ca-cert-file=/tmp/ipa-ca.crt
      - --domain=ipa.robots.org.uk
      - --hostname={{ inventory_hostname }}
      - --password={{ _ipa_client_otp }}
      - --no-ntp

  - name: etckeeper commit
    command: etckeeper commit -m ipa-client-install

- name: recon ansible user disposition
  shell: getent passwd --service=files $(id -u)
  become: false
  check_mode: false
  changed_when: false
  failed_when: false
  register: _ipa_client_ansible_user_disposition

# Can't use 'meta: end_host' because it only affects the current play; we
# want to stop subsequent plays as well, so we must deliberately fail the
# whole run.
- name: end of play, subsequent runs should use domain authentication
  fail:
    msg: ipa-client-install was run, you must re-run the playbook using domain authentication
  when: _ipa_client_ansible_user_disposition.rc == 0

- name: recon authselect state
  command: authselect current
  check_mode: false
  changed_when: false
  register: _authselect_current_raw

- name: parse authselect state
  set_fact:
    authselect_current: '{{ _authselect_current_raw.stdout | from_yaml }}'

- name: assure authselect profile
  assert:
    that: authselect_current["Profile ID"] == "sssd"

- name: enable authselect profile feature
  command: authselect enable-feature {{ item }}
  when: "'{{ item }}' not in authselect_current['Enabled features']"
  loop:
  - with-mkhomedir
  - with-subid
  - with-faillock

- name: configure pam_faillock
  lineinfile:
    path: /etc/security/faillock.conf
    line: '{{ item }}'
  loop:
  - local_users_only
  - deny = 6

# TODO: dyndns pam_gssapi pwhistory !nullok remote-access smartcard?
...
