- name: configure sshd logging
  copy:
    content: |
      LogLevel VERBOSE
    dest: /etc/ssh/sshd_config.d/10-logging.conf
    mode: 0644
    owner: root
    group: root
  notify: sshd reload

- name: configure sshd per-source block size
  copy:
    content: |
      PerSourceNetBlockSize 24:56
    dest: /etc/ssh/sshd_config.d/10-per-source.conf
    mode: 0644
    owner: root
    group: root
  notify: sshd reload

- name: check sshd config
  command:
    cmd: sshd -G
  check_mode: false
  changed_when: false

- meta: flush_handlers
