- name: add freeipa services to firewall zone
  firewalld:
    permanent: true
    immediate: true
    offline: true
    service: '{{ item }}'
    zone: public
    state: enabled
  loop:
  - dns
  - freeipa-4
...
