- name: configure PKI server logging
  copy:
    src: logging.properties
    dest: /etc/pki/pki-tomcat/logging.properties
    mode: 0644
    owner: pkiuser
    group: pkiuser
    follow: no
  notify: restart pki-tomcatd

- name: install pki-log-cleanup script
  copy:
    src: pki-log-cleanup.sh
    dest: /usr/local/sbin/pki-log-cleanup
    mode: 0755
    owner: root
    group: root

- name: install pki-log-cleanup systemd timer
  copy:
    src: pki-log-cleanup.timer
    dest: /etc/systemd/system/
    mode: 0644
    owner: root
    group: root
  notify: systemd daemon-reload

- name: install pki-log-cleanup systemd service
  template:
    src: pki-log-cleanup.service.j2
    dest: /etc/systemd/system/pki-log-cleanup.service
    mode: 0644
    owner: root
    group: root
    validate: systemd-analyze verify %s:pki-log-cleanup.service
  notify: systemd daemon-reload

- meta: flush_handlers

- name: enable & start pki-log-cleanup timer
  systemd:
    name: pki-log-cleanup.timer
    enabled: true
    state: started
...
