;[service/HTTP]
;mechs = krb5
;cred_store = keytab:/etc/gssproxy/http.keytab
;cred_store = ccache:/var/lib/gssproxy/clients/krb5cc_%U
;euid = apache

[service/md-challenge]
mechs = krb5
cred_store = client_keytab:/etc/gssproxy/acme-challenge.keytab
cred_store = ccache:/var/lib/gssproxy/clients/krb5cc_%U
cred_usage = initiate
euid = apache
socket = /var/lib/gssproxy/md-challenge.sock
