- name: create {{ conn.key }} connection file
  template:
    src: connection.j2
    dest: /etc/ipsec.d/{{ conn.key }}.conf
    owner: root
    group: root
    mode: 0644
  register: ipsec_connection_file

- name: reload {{ conn.key }}
  command: ipsec auto --replace {{ conn.key }}
  when: ipsec_connection_file.changed
