- name: create {{ conn.key }} connection file
  template:
    src: connection.j2
    dest: /etc/ipsec.d/{{ conn.key }}.conf
    owner: root
    group: root
    mode: 0644
  register: _ipsec_connection_file

- name: start {{ conn.key }} connection
  command: ipsec start {{ conn.key }}
  when: _ipsec_connection_file.changed
