- name: restart sssd
  systemd_service:
    name: sssd.service
    state: restarted

- name: reload postfix
  systemd_service:
    name: postfix.service
    state: reloaded

- name: reload dovecot
  systemd_service:
    name: dovecot.service
    state: reloaded

- name: systemctl daemon-reload
  systemd:
    daemon_reload: true

- name: stop postfix-sssd-ifp
  systemd_service:
    name: postfix-sssd-ifp.service
    state: stopped

- name: restart postfix-sssd-ifp.socket
  systemd_service:
    name: postfix-sssd-ifp.socket
    state: restarted
    enabled: true

- name: reload rspamd
  systemd_service:
    name: rspamd.service
    state: reloaded

- name: reload apache
  systemd_service:
    name: httpd.service
    state: reloaded

- name: reload gssproxy
  systemd_service:
    name: gssproxy.service
    state: reloaded
