# {{{ validate
- name: Figure SELinux module name
  set_fact:
    _selinux_policy_module_name: "{{ module_src.rstrip('.cil') | basename }}"
  when: module_src.endswith(".cil")

- name: Validate SELinux policy module name
  assert:
    that: _selinux_policy_module_name is defined
    fail_msg: SELinux policy module must be a .cil file
    success_msg: "module name: {{ _selinux_policy_module_name }}"
# }}}

# {{{ prep
- name: Create local SELinux policy module source code directory
  file:
    path: /etc/selinux/local
    state: directory
    owner: root
    group: root
    mode: 0700

- name: Install local SELinux policy module README
  copy:
    src: README
    dest: /etc/selinux/local/README
    mode: 0644
    owner: root
    group: root
# }}}}

# {{{ recon
- name: List installed SELinux policy modules
  command: semodule -l
  check_mode: false
  changed_when: false
  register: _selinux_policy_semodule_l

- name: Check for SELinux policy module {{ _selinux_policy_module_name }} source code
  stat:
    path: /etc/selinux/local/{{ module_src | basename }}
  register: _selinux_policy_module_src
# }}}

- name: Remove module actions
  when: state == "absent"
  include_tasks: remove.yml

- name: Install module actions
  when: state == "present"
  include_tasks: install.yml
